name: daily-redeploy
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Redeploy API
        run: |
          curl --request GET \
          --url '${{ secrets.FORCE_REFRESH }}' \
