name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wei/pull@1.0.0
        with:
          base: ubiquity
          upstream: transitive-bullshit:main
          mergeMethod: hardreset
